mmorpgsc/mmorpgsc/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required

from ckeditor_uploader.views import upload, browse

from mmorpgsc import settings
from wall.views import start_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', start_page),
    path('accounts/', include('allauth.urls')),
    path('accounts/signup/', include('accounts.urls')),
    path('wall/', include('wall.urls')),
    re_path(r'^upload/', login_required(upload), name='ckeditor_upload'),
    re_path(r'^browse/', login_required(never_cache(browse)), name='ckeditor_browse'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpgsc/wall/urls.py
from django.conf.urls.static import static
from django.urls import path

from .views import *


urlpatterns = [
   path('', PostList.as_view()),
   path('<int:pk>', PostDetails.as_view(), name='post_detail'),
   path('post_create/', PostCreate.as_view(), name='post_create'),
   path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('<int:pk>/reply/create', ReplyCreate.as_view(), name='reply_create'),
   path('posts_profile/', UserPostList.as_view(), name='user_posts'),
   path('replies/', reply_list, name='replies_to_user'),
   path('reply/confirm/<int:reply_id>/', confirm_reply, name='confirm_reply'),
   path('reply/cancel/<int:reply_id>/', cancel_reply, name='cancel_reply'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpgsc/wall/models.py
from django.core.cache import cache
from django.db import models
from django.urls import reverse_lazy

from ckeditor.fields import RichTextField

from mmorpgsc import settings


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='author')

    TYPE = [
        ('Tanks', 'Танки'),
        ('Healers', 'Хилы'),
        ('DD', 'ДД'),
        ('Traders', 'Торговцы'),
        ('GM', 'Гилдмастеры'),
        ('QG', 'Квестгиверы'),
        ('Smiths', 'Кузнецы'),
        ('Leatherworkers', 'Кожевники'),
        ('Potions', 'Зельевары'),
        ('Spell', 'Мастера заклинаний')]

    category = models.CharField(max_length=16, choices=TYPE, verbose_name='Category')
    name = models.CharField(max_length=128, help_text='post_name')
    content = RichTextField(config_name='default')
    time_of_creation = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def preview(self):
        return f'{self.content[0:123]}...'

    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class Reply(models.Model):

    CONFIRM_CHOICES = [
        ('unknown', 'На рассмотрении'),
        ('confirmed', 'Принят'),
        ('cancelled', 'Отклонен')]

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    reply_text = models.TextField()
    reply_date = models.DateTimeField(auto_now_add=True)
    confirm = models.CharField(max_length=16, choices=CONFIRM_CHOICES, default='unknown')

    def __str__(self):
        return self.reply_text

    def get_absolute_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.post_id})

mmorpgsc/wall/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post, Reply


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'content',
            'category',
        ]

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        content = cleaned_data.get("content")

        if name == content:
            raise ValidationError('Название и текст не должны совпадать')

        if content is not None and len(content) < 5:
            raise ValidationError({
                "content": "Содержание публикации не может быть менее 5 символов."
            })

        return cleaned_data


    def clean_name(self):
        name = self.cleaned_data["name"]
        if name[0].islower():
            raise ValidationError(
                "Название должно начинаться с заглавной буквы"
            )

        return name


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply_text',]
        widgets = {'reply_text': forms.Textarea(attrs={'rows': 3, 'cols': 70, 'placeholder': 'Введите текст отклика...'})}

    def clean(self):
        cleaned_data = super().clean()
        reply_text = cleaned_data.get("reply_text")
        if reply_text is not None and len(reply_text) < 5:
            raise ValidationError({
                "reply_text": "Содержание отклика не может быть менее 5 символов."
            })

        return cleaned_data

mmorpgsc/wall/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.template.loader import render_to_string

from accounts.models import User

from wall.filters import PostFilter
from wall.forms import ReplyForm, PostForm
from wall.models import *


def start_page(request):
    t = render_to_string('start.html')
    return HttpResponse(t)


class PostList(ListView):
    model = Post
    ordering = '-time_of_creation'
    template_name = 'wall/wall_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        all_posts = Post.objects.all().values_list('name')
        context['count_posts'] = all_posts
        context['post_count'] = f"Всего постов - {len(all_posts)}"
        context['filterset'] = self.filterset
        return context


class ReplyCreate(CreateView, LoginRequiredMixin):
    raise_exception = True
    form_class = ReplyForm
    model = Reply
    template_name = 'wall/wall_detailed.html'

    def form_valid(self, form): #валидация формы с добавлением оповещения автора поста о новом отклике
        reply = form.save(commit=False)
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        reply.user = self.request.user
        reply.post = post
        reply.post_id = self.kwargs.get('pk')
        reply.save()
        author = User.objects.get(pk=post.author_id)

        html_content = render_to_string('notifications/new_reply_notification.html',
                                        {'link': f'{settings.SITE_URL}/wall/{post.id}',
                                         'text': f'Пользователь {reply.user} оставил отклик: {reply.reply_text}'})
        msg = EmailMultiAlternatives(subject="Новый отклик на ваше объявление!", body='',
                                     from_email=settings.DEFAULT_FROM_EMAIL,
                                     to=[author.email])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()

        return super().form_valid(form)


class PostDetails(DetailView, ReplyCreate):
    model = Post
    template_name = 'wall/wall_detailed.html'
    context_object_name = 'wall_detailed'
    queryset = Post.objects.all()
    reply_form = ReplyForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['replies'] = Reply.objects.filter(post__id=self.kwargs['pk']).order_by('reply_date')
        context['form'] = self.reply_form
        return context

    def form_valid(self, form):
        form.save(commit=False)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.object.pk})


class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('wall.add_post',)
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'wall/wall_post_create.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.object.pk})


class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('wall.change_post',)
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'wall/wall_post_update.html'

    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.save(commit=False)
        return super().form_valid(form)


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('wall.delete_post',)
    raise_exception = True
    model = Post
    template_name = 'wall/wall_post_delete.html'
    success_url = "/wall/"


class UserPostList(ListView, LoginRequiredMixin):
    model = Post
    ordering = '-time_of_creation'
    template_name = 'wall/user_post_list.html'
    context_object_name = 'user_posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.filter(author=self.request.user)
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


@login_required
def reply_list(request):
    posts = Post.objects.filter(author=request.user)
    replies = Reply.objects.filter(post__in=posts)
    selected_post_id = request.GET.get('post_id')
    if selected_post_id:
        replies = replies.filter(post_id=selected_post_id)

    return render(request, 'wall/replies_to_user.html', {'posts': posts, 'replies': replies})


@login_required
def confirm_reply(request, reply_id):
    reply = get_object_or_404(Reply, id=reply_id)

    if request.user != reply.post.author:
        messages.error(request, 'Недостаточно прав для выполнения этого действия.')
        return redirect('replies_to_user')

    if reply.confirm != 'unknown':
        messages.error(request, 'Этот запрос уже обработан.')
        return redirect('replies_to_user')

    reply.confirm = 'confirmed'
    reply.save()

    subject = 'Ваш отклик принят автором объявления.'
    message = f'Ваш отклик на объявление "{reply.post.name}" принят!'
    html = (
        f'<b>{request.user.username}</b>, Ваш отклик на объявление "{reply.post.name}" принят!'
        f'<a href="http://127.0.0.1:8000/wall/{reply.post_id}">Просмотреть объявление.</a>!'
    )
    msg = EmailMultiAlternatives(
        subject=subject, body=message, from_email=None, to=[request.user.email]
    )
    msg.attach_alternative(html, "text/html")
    msg.send()

    return redirect('replies_to_user')


@login_required
def cancel_reply(request, reply_id):
    reply = get_object_or_404(Reply, id=reply_id)

    if request.user != reply.post.author:
        messages.error(request, 'Недостаточно прав для выполнения этого действия.')
        return redirect('replies_to_user')

    if reply.confirm != 'unknown':
        messages.error(request, 'Этот запрос уже обработан.')
        return redirect('replies_to_user')

    reply.confirm = 'cancelled'
    reply.save()

    subject = 'Ваш отклик отклонен автором объявления.'
    message = f'Ваш отклик на объявление "{reply.post.name}" отклонен!'
    html = (
        f'<b>{request.user.username}</b>, Ваш отклик на объявление "{reply.post.name}" отклонен!'
        f'<a href="http://127.0.0.1:8000/wall/{reply.post_id}">Просмотреть объявление.</a>!'
    )

    msg = EmailMultiAlternatives(
        subject=subject, body=message, from_email=None, to=[request.user.email]
    )
    msg.attach_alternative(html, "text/html")
    msg.send()

    return redirect('replies_to_user')

mmorpgsc/templates/wall/replies_to_user.html
{% extends 'flatpages/default.html' %}


{% block title %}
MMORPGSC
{% endblock title %}

{% block content %}

<h1>MMORPG Social Community</h1>
<h5>{{ time_now|date:'M d Y D' }}</h5>
<h2>Отклики на ваши публикации</h2>

<hr>

    <form method="GET" action="{% url 'replies_to_user' %}">
        <label for="post_id">Поиск по вашим публикациям:</label>
        <select name="post_id" id="post_id">
            <option value="">Все публикации</option>
            {% for post in posts %}
                <option value="{{ post.id }}"
                        {% if post.id == request.GET.post_id %} selected {% endif %}> {{ post.name }}
                </option>
                <p><b>Публикация: {{ response.post.name }}</b></p>
            {% endfor %}

        </select>
        <button type="submit">Поиск</button>
    </form>

<hr>

<ul class="list-group list-group-flush">
    {% if replies %}
           {% for rp in replies %}
           <li class="list-group-item">
               <p>На публикацию <a href="{% url 'post_detail' rp.post.id %}">{{ rp.post.name }}</a> пришёл отклик!</p>
               <small class="fw-bold">категория: {{ rp.post.get_category_display }} </small>
               <p>{{ rp.post.content|truncatewords:8|safe }}</p>
               <small class="fw-bold">{{ rp.reply_date|date:'M d Y D H:i' }}</small>

               <small class="fw-bold">Автор отклика: {{ rp.user }} </small>
               <small class="fw-bold">Содержание отклика: {{ rp.reply_text }} </small>

               {% if rp.confirm == 'confirmed' %}
                    <p style="color: green"><b>Отклик принят</b></p>
               {% elif rp.confirm == 'cancelled' %}
                    <p style="color: red"><b>Отклик отклонен</b></p>
               {% else %}
                    <p style="color: gray"><b>Отклик на рассмотрении</b></p>
               {% endif %}

               <hr>

               {% if rp.confirm == 'unknown' %}
               <div style="display: flex; gap: 10px; justify-content: center;">
                <form method="post" action="{% url 'confirm_reply' rp.id %}">
                    {% csrf_token %}
                    <button type="submit">Принять отклик</button>
                </form>
                <form method="post" action="{% url 'cancel_reply' rp.id %}">
                    {% csrf_token %}
                    <button type="submit">Отклонить отклик</button>
                </form>
                </div>
               {% endif %}
               <hr>
           </li>
           {% endfor %}
    {% else %}
       <h2>Откликов нет!</h2>
    {% endif %}
</ul>


{% if page_obj.has_previous %}
    <a href="?page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
       ...
    <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

   {{ page_obj.number }}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
       ...
    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% endblock content %}

mmorpgsc/templates/wall/reply_delete.html
{% extends 'flatpages/default.html' %}


{% block title %}
MMORPGSC
{% endblock title %}


{% block content %}

<h1>Удаление выбранного отклика!</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем отклик?</p>
    <input type="submit" value="Delete" />
</form>

{% endblock content %}

mmorpgsc/templates/wall/user_post_list.html
{% extends 'flatpages/default.html' %}


{% block title %}
MMORPGSC
{% endblock title %}

{% block content %}

<h1>MMORPG Social Community</h1>
<h5>{{ time_now|date:'M d Y D' }}</h5>
<h3>Ваши публикации</h3>

<form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
</form>

<hr>

{% if perms.wall.wall_post_create %}
    <a href="{% url 'post_create' %}">Добавить пост.</a>
{% endif %}


<ul class="list-group list-group-flush">
    {% if user_posts %}
           {% for user_post in user_posts %}
           <li class="list-group-item">
               <small class="fw-bold">{{ user_post.time_of_creation|date:'M d Y D H:i' }}</small>
               <a href="{% url 'post_detail' user_post.id%}">{{ user_post.name }}</a>
               <small class="fw-bold">категория:
                   {{ user_post.get_category_display }}
               </small>
               {% if user_post.author == request.user %}
                   {% if perms.wall.wall_post_update or perms.wall.wall_post_delete %}
                       <a href="{% url 'post_update' user_post.id %}">Изменить пост.</a>
                       <a href="{% url 'post_delete' user_post.id %}">Удалить пост.</a>
                   {% endif %}
               {% endif %}
               <p>{{ user_post.content|truncatewords:20|safe }}</p>
           </li>
           {% endfor %}
    {% else %}
       <h2>Публикаций нет!</h2>
    {% endif %}
</ul>


{% if page_obj.has_previous %}
    <a href="?page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
       ...
    <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

   {{ page_obj.number }}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
       ...
    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% endblock content %}

mmorpgsc/templates/wall/wall_detailed.html
{% extends 'flatpages/default.html' %}


{% block title %}
MMORPGSC
{% endblock title %}


{% block content %}
<h1> Only one single publication on site MMORPG Social Community</h1>
<hr>
   {% if wall_detailed %}

               <h1>{{ wall_detailed.name }}</h1>
               {% if wall_detailed.author == request.user %}
                   {% if perms.wall.change_post or perms.wall.delete_post %}
                       <a href="{% url 'post_update' wall_detailed.id %}">Изменить пост.</a>
                       <a href="{% url 'post_delete' wall_detailed.id %}">Удалить пост.</a>
                   {% endif %}
               {% endif %}
               <h2>{{ wall_detailed.content|safe }}</h2>
               <h6>{{ wall_detailed.time_of_creation|date:'M d Y D H:i' }}</h6>

               <hr>
               {% if perms.wall.add_reply%}
               <h4>Оставить отклик на публикацию:</h4>
               <form action="{% url 'reply_create' wall_detailed.id %}" method="post">
                   {% csrf_token %}
                   {{ form.as_p }}
                   <input type="submit" value="Оставить отклик" />
               </form>
               {% endif %}

               <h4>Все отклики на публикацию:</h4>
               {% if replies %}
                   {% for reply in replies %}
                   <small class="fw-bold">Пользователь {{ reply.user }} оставил отклик:  </small>
                   <small class="fw-bold">"{{ reply.reply_text }}"</small><br>
                   <small class="text-muted">Дата: {{ reply.reply_date }} </small><br>
                   <br>
                   <br>
                   {% endfor %}
               {% else %}
                    <h6>Откликов нет!</h6>
               {% endif %}

   {% else %}
       <h2>Публикация отсутствует!</h2>
   {% endif %}

<hr>

{% endblock content %}

mmorpgsc/templates/wall/wall_list.html
{% extends 'flatpages/default.html' %}


{% block title %}
MMORPGSC
{% endblock title %}


{% block content %}
<h1>MMORPG Social Community</h1>
<h5>{{ time_now|date:'M d Y D' }}</h5>

<form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
</form>

<hr>

{% if perms.wall.add_post %}
    <a href="{% url 'post_create' %}">Добавить пост.</a>
{% endif %}


<ul class="list-group list-group-flush">
    {% if posts %}
           {% for post in posts %}
           <li class="list-group-item">
               <small class="fw-bold">{{ post.time_of_creation|date:'M d Y D H:i' }}</small>
               <a href="{% url 'post_detail' post.id%}">{{ post.name }}</a>
               <small class="text-muted">автор: {{post.author}} </small> <br>
               <small class="fw-bold">категория:
                   {{ post.get_category_display }}
               </small>
               {% if post.author == request.user %}
                   {% if perms.wall.change_post or perms.wall.delete_post %}
                       <a href="{% url 'post_update' post.id %}">Изменить пост.</a>
                       <a href="{% url 'post_delete' post.id %}">Удалить пост.</a>
                   {% endif %}
               {% endif %}
               <p>{{ post.content|truncatewords:20|safe }}</p>
           </li>
           {% endfor %}
    {% else %}
       <h2>Публикаций нет!</h2>
    {% endif %}
</ul>



   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
<hr>

{% endblock content %}

mmorpgsc/templates/wall/wall_post_create.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Добавить новую публикацию:</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.media }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

mmorpgsc/templates/wall/wall_post_delete.html
{% extends 'flatpages/default.html' %}


{% block title %}
MMORPGSC
{% endblock title %}


{% block content %}

<h1>Удаление выбранной статьи!</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ post.name }}"?</p>
    <input type="submit" value="Delete" />
</form>

{% endblock content %}

mmorpgsc/templates/wall/wall_post_update.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Изменить публикацию:</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.media }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}